micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  application:
    name: contactReferalService
  server:
    port: 8080
  metrics:
    export:
      jmx:
        enabled: true
        step: PT1M
      statsd:
        enabled: true
        flavor: datadog
        host: localhost
        port: 8125
        step: PT1M
    enabled: true
datasources:
  default:
    url: jdbc:mysql://10.0.75.1:3306/contact-referal-user
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'contact-referal-user'
    password: 'contact-referal-user'
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
hystrix.stream.enabled: false
