micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  application:
    name: contactReferalAPI
  server:
    port: 8082
  metrics:
    export:
      jmx:
        enabled: true
        step: PT1M
      statsd:
        enabled: true
        flavor: datadog
        host: localhost
        port: 8125
        step: PT1M
    enabled: true
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
client:
  user:
    url: http://localhost:8080
  contact:
    url: http://localhost:8081
hystrix.stream.enabled: false
